Fix: treat html_block as code.
DavidAnson/markdownlint pull request #1299
Opened 2024-07-17 03:01 UTC by fyc09

Fix #1268.

`inCode` is only used in MD018, thus there are no side effects.

2024-07-17 05:25 UTC, DavidAnson commented
"Code" in the case of getLineMetadata is meant to refer to one of the two Markdown code block types (indented or fenced). The proposed change could have more side effects beyond what you have already identified. I had been thinking that a fix specific to MD018 would be best here. Did you try that first?

2024-07-17 12:39 UTC, DavidAnson commented
By the way, could you please update the test file to include scenarios that would trigger rules 18, 19, 20, and 21? If 18 is broken, then I suspect 20 is also. 19 and 21 are already migrated to micromark in the next branch, so should be OK as-is. But I would like the new test file to verify the HTML scenario for all four of these similar rules. Thank you!

2024-07-17 15:19 UTC, fyc09 commented
I'm unsure if we should investigate this violation, as the current implementation will simply ignore it.

```markdown
##Title <span>text</span> {MD018} {MD033}
```

2024-07-18 03:54 UTC, DavidAnson commented
What you show above seems like correct behavior, or am I missing something?

2024-07-18 04:03 UTC, DavidAnson requested changes
Thank you, this looks good! I left some comments on the generated file which was a mistake. Please make the suggested changes to the source files instead.

2024-07-18 04:03 UTC, DavidAnson commented on test/ignore-html-block.md
> +##Title2 {MD018}
Let's please remove all the "Title" lines so everything is testing HTML blocks.

2024-07-18 04:03 UTC, DavidAnson commented on test/ignore-html-block.md
> +#foo
"#heading", please. I try not to not use "foo"/etc.

2024-07-18 04:03 UTC, DavidAnson commented on test/ignore-html-block.md
> +</div>
Could you please add new blocks for the MD019/MD021 scenarios?

2024-07-18 04:04 UTC, DavidAnson commented
FYI, there will be a failure in TeatRepos because that is failing in next branch. I will fix that shortly, so please ignore for now.

2024-07-18 04:22 UTC, fyc09 commented
> What you show above seems like correct behavior, or am I missing something?

Currently, only MD033 is emitted; MD018 is ignored due to the HTML block in this line. I think emitting both MD033 and MD018 will be more reasonable.

2024-07-18 06:11 UTC, DavidAnson commented
I agree. But the above is an HTML span, not a block. I would not expect it to be affected by the new code?

2024-07-18 06:17 UTC, fyc09 commented
> I agree. But the above is an HTML span, not a block. I would not expect it to be affected by the new code?

You are right, I made an mistake.

2024-07-18 12:45 UTC, DavidAnson commented
Please rebase PR to latest next branch commit to fix "sh: 1: ava: not found". This is a bug in latest Node/npm which I have worked around.

2024-07-18 12:50 UTC, DavidAnson commented
I can't easily view the snapshot diff on my phone, but all the other code changes look good, thank you!

2024-07-18 13:09 UTC, DavidAnson commented
I had a look at the differences, and there is way more going on than there needs to be. After you re-base (see comment above), please run "npm run update-snapshots" to regenerate that file. The diff at that point should be ONLY the errors and corrections for the new test file you added. After that, we make sure checks pass and I'll approve. :)

2024-07-18 14:32 UTC, fyc09 commented
I reran "npm run update-snapshots", but the snapshot didn't change, and I enabled GitHub action in my own repository and the [CI](https://github.com/fyc09/markdownlint/actions/runs/9993147684) looks good. I think the tests' order is changed, but I do not know what to do.

2024-07-19 01:49 UTC, DavidAnson commented
I wonder if this is a locale issue that sorts differently for you? I will give it a try in a day or two and either push a commit to your branch with the "right" order or approve your changes as-is. Thanks again!

2024-07-20 05:32 UTC, DavidAnson approved these changes
Updating snapshots on my end worked.

2024-07-20 05:38 UTC, merged