Fix array indexing for line disable in the presence of frontmatter
DavidAnson/markdownlint pull request #469
Opened 2021-12-19 05:47 UTC by adithyabsk

* And add unit test
^ Not really sure if I set that up correctly

2021-12-19 06:20 UTC, DavidAnson requested changes
Good catch! Please update PR to be for "next" branch and fix CI issues. Thanks!

2021-12-19 06:20 UTC, DavidAnson commented on lib/markdownlint.js
> +          lineNumber + 1 + frontMatterLines.length] || {}
Put this calculation into a const so it can go back to being one line, please.

2021-12-19 06:20 UTC, DavidAnson commented on test/front-matter-ignore-line.md
> +<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="http:www.google.com/very+long+url"></iframe>
This could be any HTML and the suppression just for the "inline-html" rule, I think?

2021-12-19 06:20 UTC, DavidAnson commented on test/front-matter-ignore-line.md
> +---
File name: front-matter-with-disable-next-line.md

2021-12-19 06:20 UTC, DavidAnson commented on test/front-matter-ignore-line.md
> +
Please add another kind of violation and suppression below, after a line with a valid reported violation via {MDxxx}, please.

2021-12-19 06:23 UTC, DavidAnson commented on test/front-matter-ignore-line.md
> +<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="http:www.google.com/very+long+url"></iframe>
Specifically, please use a simpler example like "<hr>".

2021-12-19 06:25 UTC, DavidAnson commented on test/front-matter-ignore-line.md
> +
For example:

Front matter

Disabled violation

Violation

Disabled violation

2021-12-23 03:34 UTC, DavidAnson commented
I made the changes I asked for and pushed a commit based on yours here: https://github.com/DavidAnson/markdownlint/commit/5253669495e7e57aebdccd8822c8c2e311c56f1f

Thanks for reporting this!

2021-12-23 03:34 UTC, closed without merging

2021-12-24 00:13 UTC, adithyabsk commented
@DavidAnson thanks for getting this merged in! Sorry, I was tied up and couldn't get to it sooner.

2021-12-24 00:21 UTC, DavidAnson commented
No worries, you made a great one line fix and I felt like I was asking for a ton of changes.