fix: Make MD040/fenced-code-language case sensitive.
DavidAnson/markdownlint pull request #628
Opened 2022-11-05 17:17 UTC by regseb

Fix #627.

2022-11-05 17:28 UTC, DavidAnson requested changes
This is great, thank you for doing this!

Looks like the generated file needs to be added to pass CI. Could you also please make a tiny update to doc-build/md040.md to mention case is sensitive for this rule?

2022-11-05 17:28 UTC, DavidAnson commented on lib/md040.js
> +      } else if (allowed.length > 0 && !allowed.includes(lang)) {
Please add parents around the length comparison.

2022-11-05 17:28 UTC, DavidAnson commented on test/md040-allowed_languages.md
> +Code block with `MD` (uppercase) not in allowed_languages:
Nice, thanks for adding both to be sure!

2022-11-05 18:15 UTC, regseb commented
I added the parenthesis and a sentence in the documentation. I ran all `build-*`.

I also removed the trim for comparison with allowed languages so this code reports an error:

````markdown
<!-- markdownlint-configure-file { "MD040": { "allowed_languages": ["js"] } } -->
``` js
// ^ Space!
let foo = "bar";
```
````

2022-11-05 21:00 UTC, DavidAnson commented
The specifications says that the info string is trimmed of leading and trailing whitespace, so I do not think it is appropriate to remove the call to `trim`: https://spec.commonmark.org/0.30/#fenced-code-blocks

2022-11-05 21:25 UTC, nschonni commented
Might need a test for extra metadata like https://spec.commonmark.org/0.30/#example-143 or just validate that the first token is in the allowlist, and ignore the rest

2022-11-05 21:35 UTC, DavidAnson commented
Great point! I am happy to add that myself in a separate commit, or it would be fine to include here.

2022-11-05 21:51 UTC, regseb commented
I re-added the trim and only check the first word.

I would like to have a way to compare all the _info string_ with the allowed languages. Maybe add a `strict` option that bypass `.trim().split(/\s+/u).shift()`?

2022-11-05 22:12 UTC, DavidAnson commented
Only the first "word" of the info string is the language, right? That should be present so the code can be formatted properly. But the rest of the line is a mystery. It may be used to format better, but I'd worry about a setting that blocks if it may be needed for some cases?

2022-11-06 00:39 UTC, DavidAnson approved these changes
Thanks for the contribution!

2022-11-06 00:41 UTC, merged