feat(fenced-code-language): Add option to refuse extra data
DavidAnson/markdownlint pull request #629
Opened 2022-11-06 09:13 UTC by regseb

Add option to refuse leading and trailing whitespace; and extra data in fence code blocks information.

PR related:  #628 and #610

2022-11-07 02:37 UTC, DavidAnson requested changes
I think this is a good idea, and I like the behavior you have implemented! I left a few comments about how this PR might be tweaked. Thanks!

2022-11-07 02:37 UTC, DavidAnson commented on demo/markdownlint-browser.js
> +            if (!extra && token.info !== lang) {
Parenthesis, please.

2022-11-07 02:37 UTC, DavidAnson commented on demo/markdownlint-browser.js
> +        extra = (extra === undefined) ? true : !!extra;
I prefer to default unset parameters to false. Could this be reframed as "language_only"? (Not sure I love that name, but you get the idea.)

2022-11-07 02:37 UTC, DavidAnson commented on doc-build/md040.md
> +You have the option to refuse extra data in fence code blocks information. To do
I may have future comments on the phrasing here, but will wait until we agree on the parameter name.

2022-11-07 02:37 UTC, DavidAnson commented on test/md040-extra.md
> +<h1>markdownlint</h1>  {MD040:5}
Nit: Extra space

2022-11-07 02:37 UTC, DavidAnson commented on test/md040-extra.md
> +# md040-extra.md
Love the new test cases!

2022-11-07 02:37 UTC, DavidAnson commented on test/md040-extra.md
> +body {}  {MD040:11} {MD009:11}
It's not unreasonable, but should we really warn for both rules in this scenario? Per the specification, trailing white space will already be removed and so is harmless and arguably not "extra" data. I'm thinking maybe only the trailing white space rule should report for this example. What do you think?

2022-11-07 19:11 UTC, regseb commented
My proposals for the name of the parameter (from best to worst): `strict`, `language_only`, `no_extra`, `no_extra_data`, `one_word`, `single`.

---

With the `language_only` option, I expect the first line of the fenced code block to contain only the language (without spaces).

The two rules `no-trailing-spaces` and `fenced-code-language` check the same thing, but they don't have the same scope. Maybe a user only wants to check the language strictly. If we don't check the trailing spaces in the _info string_: the user won't get the information about the extra spaces.

The best thing to do would be to add a parameter to the `no-trailing-spaces` rule to not check for trailing spaces for fences. Personally, I wouldn't activate this parameter because I don't mind having two errors for the same case. I think this option would be superfluous.

2022-11-08 05:43 UTC, DavidAnson commented
I don't like `strict` for this, so let's go with `language_only` - and it looks like you've already made that change. I'm fine with the overlap in trailing spaces we have now. I'll make a second review pass shortly. Thanks!

2022-11-08 06:13 UTC, DavidAnson requested changes
Looking good, just a few more comments...

2022-11-08 06:13 UTC, DavidAnson commented on lib/md040.js
> +    const only = !!params.config.language_only;
Please call it `languageOnly` for consistency.

2022-11-08 06:13 UTC, DavidAnson commented on lib/md040.js
> +          `"${token.info}" doesn't only contain the language`
Info string contains more than language: "${token.info}"

2022-11-08 06:13 UTC, DavidAnson commented on schema/build-config-schema.js
> +          "description": "Accept language only",
"Accept" -> "Require"

2022-11-08 06:13 UTC, DavidAnson commented on test/md040-language_only.md
> +Fence code block information with leading whitespaces:
"whitespace" (no 's')

2022-11-08 06:13 UTC, DavidAnson commented on doc-build/md040.md
> +You have the option to refuse extra data in fence code blocks information. To do
How about:

You can prevent extra data from being present in the info string of fenced code blocks. To do so, set the `language_only` parameter to `true`.
 <!-- markdownlint-disable-next-line no-space-in-code -->
 Info strings with leading/trailing whitespace (ex: `  js  `) or other content (ex: `ruby startline=3`) will trigger this rule.

2022-11-08 06:13 UTC, DavidAnson commented on test/md040-language_only.md
> +body {}  {MD040:11} {MD009:11}
Extra space

2022-11-10 16:29 UTC, regseb commented
I fixed your feedback. For the text in English, I trust you. _(Google Translate est mon ami)_

2022-11-11 06:03 UTC, DavidAnson approved these changes
Thank you!

2022-11-11 06:07 UTC, merged